//trycatch

const num1 = 20;
const num2 = 10;

try {
    console.log(num2);
} catch (error) {
    console.log(error);
}
